#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Shift\Cli\Commands\DiscoverCommand;
use Shift\Cli\Commands\PublishCommand;
use Shift\Cli\Commands\RunCommand;
use Shift\Cli\Support\TaskManifest;
use Symfony\Component\Console\Application;

$taskManifest = new TaskManifest(getenv('COMPOSER_VENDOR_DIR') ?: getcwd() . '/vendor');

$application = new Application();
$application->add(new DiscoverCommand($taskManifest));
$application->add(new PublishCommand());
$application->add(new RunCommand($taskManifest));
$application->setDefaultCommand('run');
$application->run();
