#!/usr/bin/env php
<?php
// application.php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Shift\Cli\Commands\DiscoverCommand;
//use Shift\Cli\Commands\HelpCommand;
use Shift\Cli\Commands\RunCommand;
use Shift\Cli\Commands\PublishCommand;

$command = new RunCommand();
$application = new Application();
$application->add($command);
$application->setDefaultCommand($command->getName());
$application->run();
